### ISSUE TITLE
Hard coded domain name?

### ISSUE THREAD

**Issue by rangivon** [donvang05/Exchange-mailbox-size-for-zabbix-3.4#1]
Hi,
the domain name is hard coded into the code.
you might wish to use this:

#requires -version 3

<#
.SYNOPSIS
    Requrired PowerShell 3.0 or higher
.DESCRIPTION
  This sricpt using for LLD and trapper
.PARAMETER <ActionType>
	Type of action: discover, get and other
.PARAMETER <Key>
	Key - attirbute for 	
.PARAMETER <Value>
	Value - var for key, may be single or multiply
.INPUTS
  Input 3 variables

.OUTPUTS
  Output in JSON format for Zabbix in Discover - 
  single data line for other functions
.NOTES
  Version:        1.0
  Author:         donvang05@gmail..com	
  Creation Date:  17/10/2018
    
.EXAMPLE
  exch_host.ps1 -ActionType "$1" -Key "$2" -Value "$3"
#>

Param(
    [Parameter(Mandatory = $true)][String]$ActionType,
    [Parameter(Mandatory = $true)][String]$Key,
    [Parameter(Mandatory = $false)][String]$Value
)
# to use Exchange management shell 
add-pssnapin Microsoft.Exchange.Management.PowerShell.E2010  
$ActionType = $ActionType.ToLower()
$Key = $Key.ToLower()
$Value = $Value.ToLower()

$DomainName = "XXXX\"   # ex. "CONTOSO\"
$FullMBXName

# it is need for correct cyrilic symbols in old OS
# [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

	
if ($ActionType -eq "discover") {
    # Discover MAILBOSES 
    if ($Key -eq "mailbox") {	
      $result_json = [pscustomobject]@{
            'data' = @(
                get-mailbox  | ForEach-Object {
                    $mailbox_alias = $_.alias;
                    [pscustomobject]@{
                        '{#MAILALIAS}' = $mailbox_alias.ToLower()
                    }
                }					
            )
        }| ConvertTo-Json

        [Console]::WriteLine($result_json)
    }
 }

if ($ActionType -eq "get") {
    # get mailbox size 
    $FullMBXName = $DomainName + "" + $Key
    $mailbox_size = Get-MailboxStatistics $FullMBXName 
    $mailbox_size = $mailbox_size.TotalItemSize.Value.tobytes()
    [Console]::WriteLine($mailbox_size)
  
}

if ($ActionType -eq "deletedfoldersize") {
	# Get deleted folder size with subfolders
    $mailbox_size  = ""
    $size = 0 
    $FullMBXName = $DomainName + "" + $Key
    Get-MailboxfolderStatistics -Identity $FullMBXName -folderscope DeletedItems | ForEach-Object {
        $size = $size + $_.FolderSize.tobytes()
    }
    
    $mailbox_size = $size
    [Console]::WriteLine($mailbox_size)
}

if ($ActionType -eq "sentitemsfoldersize") {
	# get sent Items folder size
    $mailbox_size  = ""
    $size = 0 
    $FullMBXName = $DomainName + "" + $Key
    
    Get-MailboxfolderStatistics -Identity $FullMBXName -folderscope SentItems | ForEach-Object {
        $size = $size + $_.FolderSize.tobytes()
    }
    $mailbox_size = $size
    [Console]::WriteLine($mailbox_size)
}

**Comment by donvang05** [comment]
I have changed it now.. thank you for letting me know.
